version: '3.8'

services:
  app:
#    image: 'dockerspring:latest'
    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgre:/var/lib/postgres
      - postgreconfig:/etc/config

volumes:
  postgre:
  postgreconfig: